-- ============================================
-- SCRIPT DE CREACIÓN DE TABLAS
-- Lucas1
-- ============================================

CREATE TABLE student (
    student_code        VARCHAR2(20) PRIMARY KEY,
    document_type       CHAR(1) NOT NULL,
    document_number     VARCHAR2(20) NOT NULL,
    name                VARCHAR2(100) NOT NULL,
    last_name           VARCHAR2(100) NOT NULL,
    phone_number        CHAR(9),
    email               VARCHAR2(150),
    password            VARCHAR2(250) NOT NULL,
    registration_date   TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE course (
    course_code     VARCHAR2(10) PRIMARY KEY,
    title           VARCHAR2(200) NOT NULL,
    description     CLOB,
    category        VARCHAR2(100) NOT NULL,
    instructor      VARCHAR2(150) NOT NULL,
    creation_date   TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE module (
    module_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_code     VARCHAR2(10) NOT NULL,
    title           VARCHAR2(200) NOT NULL,
    sequence_number NUMBER
);

CREATE TABLE enrollment (
    enrollment_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_code    VARCHAR2(20) NOT NULL,
    course_code     VARCHAR2(10) NOT NULL,
    enrollment_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE student_progress (
    progress_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enrollment_id   NUMBER NOT NULL,
    module_id       NUMBER NOT NULL,
    completed       CHAR(1) CHECK (completed IN ('Y','N')),
    completion_date DATE
);
