-- Tablas de Karla2 (Dev2)

CREATE TABLE module (
    module_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_code     VARCHAR2(10) NOT NULL,
    title           VARCHAR2(200) NOT NULL,
    sequence_number NUMBER
);

CREATE TABLE enrollment (
    enrollment_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_code    VARCHAR2(20) NOT NULL,
    course_code     VARCHAR2(10) NOT NULL,
    enrollment_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
