-- Tablas de Luis3 (Dev3)

CREATE TABLE student_progress (
    progress_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enrollment_id   NUMBER NOT NULL,
    module_id       NUMBER NOT NULL,
    completed       CHAR(1) CHECK (completed IN ('Y','N')),
    completion_date DATE
);
